### ISSUE TITLE
api-key dialog is ugly

### ISSUE THREAD

**Issue by mulyoved** [terror2012/electronApp#6]
![image](https://user-images.githubusercontent.com/2309907/101765524-19877c80-3aea-11eb-802a-482ad07abc01.png)

**Comment by terror2012** [comment]
Because electron natively doesn't support prompts (since they block the thread), I used electron-prompt package that has a fixed height set, and since it uses OS native fonts, depending on the system, it will be a bit different.
Default height shows everything properly but shows a scrollbar that I can't hide with css, and if I put too much height, the buttons aren't aligned.

**Comment by mulyoved** [comment]
OK, can be closed
